// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/auth/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/auth/ports.go -destination=internal/usecase/auth/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	models "github.com/rwrrioe/sso/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUserSaver is a mock of UserSaver interface.
type MockUserSaver struct {
	ctrl     *gomock.Controller
	recorder *MockUserSaverMockRecorder
	isgomock struct{}
}

// MockUserSaverMockRecorder is the mock recorder for MockUserSaver.
type MockUserSaverMockRecorder struct {
	mock *MockUserSaver
}

// NewMockUserSaver creates a new mock instance.
func NewMockUserSaver(ctrl *gomock.Controller) *MockUserSaver {
	mock := &MockUserSaver{ctrl: ctrl}
	mock.recorder = &MockUserSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSaver) EXPECT() *MockUserSaverMockRecorder {
	return m.recorder
}

// SaveUser mocks base method.
func (m *MockUserSaver) SaveUser(ctx context.Context, email string, passHash []byte) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", ctx, email, passHash)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockUserSaverMockRecorder) SaveUser(ctx, email, passHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockUserSaver)(nil).SaveUser), ctx, email, passHash)
}

// MockUserProvider is a mock of UserProvider interface.
type MockUserProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUserProviderMockRecorder
	isgomock struct{}
}

// MockUserProviderMockRecorder is the mock recorder for MockUserProvider.
type MockUserProviderMockRecorder struct {
	mock *MockUserProvider
}

// NewMockUserProvider creates a new mock instance.
func NewMockUserProvider(ctrl *gomock.Controller) *MockUserProvider {
	mock := &MockUserProvider{ctrl: ctrl}
	mock.recorder = &MockUserProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProvider) EXPECT() *MockUserProviderMockRecorder {
	return m.recorder
}

// IsAdmin mocks base method.
func (m *MockUserProvider) IsAdmin(ctx context.Context, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdmin", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAdmin indicates an expected call of IsAdmin.
func (mr *MockUserProviderMockRecorder) IsAdmin(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdmin", reflect.TypeOf((*MockUserProvider)(nil).IsAdmin), ctx, userID)
}

// SetNewPassword mocks base method.
func (m *MockUserProvider) SetNewPassword(ctx context.Context, email string, passHash []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNewPassword", ctx, email, passHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNewPassword indicates an expected call of SetNewPassword.
func (mr *MockUserProviderMockRecorder) SetNewPassword(ctx, email, passHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNewPassword", reflect.TypeOf((*MockUserProvider)(nil).SetNewPassword), ctx, email, passHash)
}

// User mocks base method.
func (m *MockUserProvider) User(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockUserProviderMockRecorder) User(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockUserProvider)(nil).User), ctx, email)
}

// MockAppProvider is a mock of AppProvider interface.
type MockAppProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAppProviderMockRecorder
	isgomock struct{}
}

// MockAppProviderMockRecorder is the mock recorder for MockAppProvider.
type MockAppProviderMockRecorder struct {
	mock *MockAppProvider
}

// NewMockAppProvider creates a new mock instance.
func NewMockAppProvider(ctrl *gomock.Controller) *MockAppProvider {
	mock := &MockAppProvider{ctrl: ctrl}
	mock.recorder = &MockAppProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppProvider) EXPECT() *MockAppProviderMockRecorder {
	return m.recorder
}

// App mocks base method.
func (m *MockAppProvider) App(ctx context.Context, appID int) (*models.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "App", ctx, appID)
	ret0, _ := ret[0].(*models.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// App indicates an expected call of App.
func (mr *MockAppProviderMockRecorder) App(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "App", reflect.TypeOf((*MockAppProvider)(nil).App), ctx, appID)
}

// MockRefreshTokenProvider is a mock of RefreshTokenProvider interface.
type MockRefreshTokenProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenProviderMockRecorder
	isgomock struct{}
}

// MockRefreshTokenProviderMockRecorder is the mock recorder for MockRefreshTokenProvider.
type MockRefreshTokenProviderMockRecorder struct {
	mock *MockRefreshTokenProvider
}

// NewMockRefreshTokenProvider creates a new mock instance.
func NewMockRefreshTokenProvider(ctrl *gomock.Controller) *MockRefreshTokenProvider {
	mock := &MockRefreshTokenProvider{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenProvider) EXPECT() *MockRefreshTokenProviderMockRecorder {
	return m.recorder
}

// DeleteToken mocks base method.
func (m *MockRefreshTokenProvider) DeleteToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockRefreshTokenProviderMockRecorder) DeleteToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToken", reflect.TypeOf((*MockRefreshTokenProvider)(nil).DeleteToken), ctx, token)
}

// MarkUsed mocks base method.
func (m *MockRefreshTokenProvider) MarkUsed(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsed", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUsed indicates an expected call of MarkUsed.
func (mr *MockRefreshTokenProviderMockRecorder) MarkUsed(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsed", reflect.TypeOf((*MockRefreshTokenProvider)(nil).MarkUsed), ctx, token)
}

// RefreshToken mocks base method.
func (m *MockRefreshTokenProvider) RefreshToken(ctx context.Context, token string) (*models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, token)
	ret0, _ := ret[0].(*models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockRefreshTokenProviderMockRecorder) RefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockRefreshTokenProvider)(nil).RefreshToken), ctx, token)
}

// SaveRefreshToken mocks base method.
func (m *MockRefreshTokenProvider) SaveRefreshToken(ctx context.Context, token, uid string, appID int, expiresAt time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRefreshToken", ctx, token, uid, appID, expiresAt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveRefreshToken indicates an expected call of SaveRefreshToken.
func (mr *MockRefreshTokenProviderMockRecorder) SaveRefreshToken(ctx, token, uid, appID, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRefreshToken", reflect.TypeOf((*MockRefreshTokenProvider)(nil).SaveRefreshToken), ctx, token, uid, appID, expiresAt)
}

// MockResetTokenProvider is a mock of ResetTokenProvider interface.
type MockResetTokenProvider struct {
	ctrl     *gomock.Controller
	recorder *MockResetTokenProviderMockRecorder
	isgomock struct{}
}

// MockResetTokenProviderMockRecorder is the mock recorder for MockResetTokenProvider.
type MockResetTokenProviderMockRecorder struct {
	mock *MockResetTokenProvider
}

// NewMockResetTokenProvider creates a new mock instance.
func NewMockResetTokenProvider(ctrl *gomock.Controller) *MockResetTokenProvider {
	mock := &MockResetTokenProvider{ctrl: ctrl}
	mock.recorder = &MockResetTokenProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResetTokenProvider) EXPECT() *MockResetTokenProviderMockRecorder {
	return m.recorder
}

// MarkResetTokenUsed mocks base method.
func (m *MockResetTokenProvider) MarkResetTokenUsed(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkResetTokenUsed", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkResetTokenUsed indicates an expected call of MarkResetTokenUsed.
func (mr *MockResetTokenProviderMockRecorder) MarkResetTokenUsed(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkResetTokenUsed", reflect.TypeOf((*MockResetTokenProvider)(nil).MarkResetTokenUsed), ctx, token)
}

// ResetToken mocks base method.
func (m *MockResetTokenProvider) ResetToken(ctx context.Context, token string) (*models.ResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetToken", ctx, token)
	ret0, _ := ret[0].(*models.ResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetToken indicates an expected call of ResetToken.
func (mr *MockResetTokenProviderMockRecorder) ResetToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetToken", reflect.TypeOf((*MockResetTokenProvider)(nil).ResetToken), ctx, token)
}

// SaveResetToken mocks base method.
func (m *MockResetTokenProvider) SaveResetToken(ctx context.Context, token, email string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveResetToken", ctx, token, email, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveResetToken indicates an expected call of SaveResetToken.
func (mr *MockResetTokenProviderMockRecorder) SaveResetToken(ctx, token, email, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveResetToken", reflect.TypeOf((*MockResetTokenProvider)(nil).SaveResetToken), ctx, token, email, ttl)
}
