grpc_port: 9081
logger_type: local

redis:
  address: "localhost:6379"
  password: ""
  db: 1
  protocol: 2

resend:
  from: "test@gmail.com"
  name: "Test SSO"

auth:
  access_token_ttl: 15m
  refresh_token_ttl: 720h
  reset_token_ttl: 1h

code:
  code_ttl: 5m