// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/code/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/code/ports.go -destination=internal/usecase/code/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/rwrrioe/sso/internal/domain/models"
	code "github.com/rwrrioe/sso/internal/usecase/code"
	gomock "go.uber.org/mock/gomock"
)

// MockCodeProvider is a mock of CodeProvider interface.
type MockCodeProvider struct {
	ctrl     *gomock.Controller
	recorder *MockCodeProviderMockRecorder
	isgomock struct{}
}

// MockCodeProviderMockRecorder is the mock recorder for MockCodeProvider.
type MockCodeProviderMockRecorder struct {
	mock *MockCodeProvider
}

// NewMockCodeProvider creates a new mock instance.
func NewMockCodeProvider(ctrl *gomock.Controller) *MockCodeProvider {
	mock := &MockCodeProvider{ctrl: ctrl}
	mock.recorder = &MockCodeProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeProvider) EXPECT() *MockCodeProviderMockRecorder {
	return m.recorder
}

// Code mocks base method.
func (m *MockCodeProvider) Code(ctx context.Context, codeHash string) (*models.ResetCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Code", ctx, codeHash)
	ret0, _ := ret[0].(*models.ResetCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Code indicates an expected call of Code.
func (mr *MockCodeProviderMockRecorder) Code(ctx, codeHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Code", reflect.TypeOf((*MockCodeProvider)(nil).Code), ctx, codeHash)
}

// MarkCodeUsed mocks base method.
func (m *MockCodeProvider) MarkCodeUsed(ctx context.Context, codeHash string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCodeUsed", ctx, codeHash, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCodeUsed indicates an expected call of MarkCodeUsed.
func (mr *MockCodeProviderMockRecorder) MarkCodeUsed(ctx, codeHash, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCodeUsed", reflect.TypeOf((*MockCodeProvider)(nil).MarkCodeUsed), ctx, codeHash, ttl)
}

// SaveCode mocks base method.
func (m *MockCodeProvider) SaveCode(ctx context.Context, uid, codeHash string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCode", ctx, uid, codeHash, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCode indicates an expected call of SaveCode.
func (mr *MockCodeProviderMockRecorder) SaveCode(ctx, uid, codeHash, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCode", reflect.TypeOf((*MockCodeProvider)(nil).SaveCode), ctx, uid, codeHash, ttl)
}

// MockMailProvider is a mock of MailProvider interface.
type MockMailProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMailProviderMockRecorder
	isgomock struct{}
}

// MockMailProviderMockRecorder is the mock recorder for MockMailProvider.
type MockMailProviderMockRecorder struct {
	mock *MockMailProvider
}

// NewMockMailProvider creates a new mock instance.
func NewMockMailProvider(ctrl *gomock.Controller) *MockMailProvider {
	mock := &MockMailProvider{ctrl: ctrl}
	mock.recorder = &MockMailProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailProvider) EXPECT() *MockMailProviderMockRecorder {
	return m.recorder
}

// SendCode mocks base method.
func (m *MockMailProvider) SendCode(ctx context.Context, email, arg2 string, codeType code.CodeType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCode", ctx, email, arg2, codeType)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCode indicates an expected call of SendCode.
func (mr *MockMailProviderMockRecorder) SendCode(ctx, email, arg2, codeType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCode", reflect.TypeOf((*MockMailProvider)(nil).SendCode), ctx, email, arg2, codeType)
}

// MockUserProvider is a mock of UserProvider interface.
type MockUserProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUserProviderMockRecorder
	isgomock struct{}
}

// MockUserProviderMockRecorder is the mock recorder for MockUserProvider.
type MockUserProviderMockRecorder struct {
	mock *MockUserProvider
}

// NewMockUserProvider creates a new mock instance.
func NewMockUserProvider(ctrl *gomock.Controller) *MockUserProvider {
	mock := &MockUserProvider{ctrl: ctrl}
	mock.recorder = &MockUserProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProvider) EXPECT() *MockUserProviderMockRecorder {
	return m.recorder
}

// User mocks base method.
func (m *MockUserProvider) User(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockUserProviderMockRecorder) User(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockUserProvider)(nil).User), ctx, email)
}
